services:
  pgsql:
    image: postgres:16
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      PGPASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE:-default}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - vpgsql:/var/lib/postgresql/data
    networks:
      - net
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-default}", "-U", "${DB_USER}"]
      retries: 3
      timeout: 5s
  
  user-service:
    image: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/user-service/.env
    environment:
      - NODE_ENV=${USER_SERVICE_BUILD_TARGET:-production}
      - HOST=0.0.0.0
      - DB_HOST=pgsql
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-default}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    restart: always
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
      - /app/build
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - net

  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pgsql
      - user-service
    networks:
      - net
    
networks:
  net:
    driver: bridge

volumes:
  vpgsql: