/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     *  (checkHealth)
     * @description Returns **200** (OK) as **text/plain**
     *
     *      _app/controllers/health_controller.ts_ - **checkHealth**
     */
    get: operations['checkHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     *  (register)
     * @description Register a new user
     *
     *      _app/controllers/auth_controller.ts_ - **register**
     */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     *  (login)
     * @description Log in a user
     *
     *      _app/controllers/auth_controller.ts_ - **login**
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     *  (logout)
     * @description Log out the current user using the access token in the Authorization header (Bearer ${token})
     *
     *      _app/controllers/auth_controller.ts_ - **logout**
     */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     *  (me)
     * @description Returns **200** (OK) as **application/json**
     *
     *      _app/controllers/auth_controller.ts_ - **me**
     */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a list of  (index)
     * @description
     *
     *      _app/controllers/users_controller.ts_ - **index**
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Returns **401** (Unauthorized) */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Returns **403** (Forbidden) */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a single instance of :id (show)
     * @description
     *
     *      _app/controllers/users_controller.ts_ - **show**
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Returns **401** (Unauthorized) */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Returns **403** (Forbidden) */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    /**
     * Update :id (update)
     * @description
     *
     *      _app/controllers/users_controller.ts_ - **update**
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        /** @description Returns **401** (Unauthorized) */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Returns **403** (Forbidden) */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    /**
     * Delete :id (destroy)
     * @description
     *
     *      _app/controllers/users_controller.ts_ - **destroy**
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Returns **401** (Unauthorized) */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Returns **403** (Forbidden) */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/relations/{id}/patients': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     *  (getPatients)
     * @description Returns **200** (OK) as **application/json**
     *
     *      _app/controllers/user_relations_controller.ts_ - **getPatients**
     */
    get: operations['getPatients']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/relations/{id}/related-users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     *  (getRelatedUsers)
     * @description Returns **200** (OK) as **application/json**
     *
     *      _app/controllers/user_relations_controller.ts_ - **getRelatedUsers**
     */
    get: operations['getRelatedUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/relations/link': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     *  (linkPatient)
     * @description Link a patient to a doctor, nurse, or relative
     *
     *      _app/controllers/user_relations_controller.ts_ - **linkPatient**
     */
    post: operations['linkPatient']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/relations/unlink': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     *  (unlinkPatient)
     * @description Unlink a patient from a doctor, nurse, or relative
     *
     *      _app/controllers/user_relations_controller.ts_ - **unlinkPatient**
     */
    post: operations['unlinkPatient']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Any JSON object not defined as schema */
    Any: unknown
    PaginationMeta: {
      /** @example 100 */
      total?: number
      /** @example 2 */
      page?: number
      /** @example 10 */
      perPage?: number
      /** @example 3 */
      currentPage?: number
      /** @example 10 */
      lastPage?: number
      /** @example 1 */
      firstPage?: number
      /** @example /?page=10 */
      lastPageUrl?: string
      /** @example /?page=1 */
      firstPageUrl?: string
      /** @example /?page=6 */
      nextPageUrl?: string
      /** @example /?page=5 */
      previousPageUrl?: string
    }
    /** @description TokenInterface (Interface) */
    TokenInterface: {
      /** @example Lorem Ipsum */
      type?: string
      /** @example John Doe */
      name?: string
      /** @example Lorem Ipsum */
      token?: string
      abilities?: string[]
      /** @example Lorem Ipsum */
      lastUsedAt?: string
      /** @example Lorem Ipsum */
      expiresAt?: string
    }
    /** @description LoginResponseInterface (Interface) */
    LoginResponseInterface: {
      /** @example null */
      user?: components['schemas']['User']
      /** @example null */
      token?: components['schemas']['TokenInterface']
      /** @example Lorem Ipsum */
      success?: string
    }
    /** @description Patient (Interface) */
    Patient: {
      /** @example 179 */
      id?: number
      /** @example 446 */
      userId?: number
      /** @example 681 */
      relatedUserId?: number
      /** @example Lorem Ipsum */
      relationType?: string
      /** @example Lorem Ipsum */
      createdAt?: string
      /** @example Lorem Ipsum */
      updatedAt?: string
      /** @example null */
      user?: components['schemas']['User']
    }
    /** @description GetPatientsResponseInterface (Interface) */
    GetPatientsResponseInterface: {
      patients?: components['schemas']['Patient'][]
      /** @example Lorem Ipsum */
      success?: string
    }
    /** @description LinkPatientResponseInterface (Interface) */
    LinkPatientResponseInterface: {
      /** @example Lorem Ipsum */
      message?: string
      /** @example true */
      success?: boolean
      /** @example null */
      userRelation?: components['schemas']['UserRelation']
    }
    /** @description UnlinkPatientResponseInterface (Interface) */
    UnlinkPatientResponseInterface: {
      /** @example Lorem Ipsum */
      message?: string
      /** @example true */
      success?: boolean
    }
    /** @description GetRelationsResponseInterface (Interface) */
    GetRelationsResponseInterface: {
      /** @example null */
      doctor?: components['schemas']['UserRelation']
      /** @example null */
      nurse?: components['schemas']['UserRelation']
      relatives?: components['schemas']['UserRelation'][]
      /** @example true */
      success?: boolean
    }
    /** @description BloodPressure (Model) */
    BloodPressure: {
      /** @example 227 */
      id?: number
      /** @example 37 */
      systolic?: number
      /** @example 883 */
      diastolic?: number
    }
    /** @description HealthRecord (Model) */
    HealthRecord: {
      /** @example 705 */
      id?: number
      /**
       * Format: date-time
       * @example 2021-03-23T16:13:08.489+01:00
       */
      timestamp?: string
      /** @example 277 */
      bloodPressureId?: number
      /** @example null */
      bloodPressure?: components['schemas']['BloodPressure']
      /** @example 930 */
      userId?: number
      /** @example null */
      user?: components['schemas']['User']
      /** @example 359 */
      heartRate?: number
      /** @example 586 */
      stressLevel?: number
      /** @example 652 */
      bloodOxygenation?: number
      /** @example 298 */
      bodyTemperature?: number
      /** @example 329 */
      acceleration?: number
    }
    /** @description SleepPace (Model) */
    SleepPace: {
      /** @example 214 */
      id?: number
      /**
       * Format: date-time
       * @example 2021-03-23T16:13:08.489+01:00
       */
      timestamp?: string
      /** @example 762 */
      userId?: number
      /** @example null */
      user?: components['schemas']['User']
      /** @example 479 */
      sleepDuration?: number
      /** @example 640 */
      lightSlowSleep?: number
      /** @example 82 */
      deepSlowSleep?: number
      /** @example 119 */
      deepSlowParadoxSleep?: number
      /** @example 105 */
      paradoxSleep?: number
    }
    /** @description User (Model) */
    User: {
      /** @example 977 */
      id?: number
      /** @example John */
      firstName?: string
      /** @example Doe */
      lastName?: string
      /**
       * Format: email
       * @example johndoe@example.com
       */
      email?: string
      /** @example Lorem Ipsum */
      phoneNumber?: string
      /** @example 1028 Farland Street */
      address?: string
      /** @example Lorem Ipsum */
      birthDate?: string
      /**
       * @example 'PATIENT'
       * @enum {string}
       */
      role?: "'PATIENT'" | "'RELATIVE'" | "'DOCTOR'" | "'NURSE'" | "'ADMIN'"
      patients?: components['schemas']['UserRelation'][]
      doctor?: components['schemas']['UserRelation'][]
      nurse?: components['schemas']['UserRelation'][]
      relatives?: components['schemas']['UserRelation'][]
      healthRecords?: components['schemas']['HealthRecord'][]
      sleepPaces?: components['schemas']['SleepPace'][]
      /**
       * Format: date-time
       * @example 2021-03-23T16:13:08.489+01:00
       */
      createdAt?: string
      /**
       * Format: date-time
       * @example 2021-03-23T16:13:08.489+01:00
       */
      updatedAt?: string
    }
    /** @description UserRelation (Model) */
    UserRelation: {
      /** @example 358 */
      id?: number
      /** @example 415 */
      userId?: number
      /** @example 895 */
      relatedUserId?: number
      /**
       * @example 'DOCTOR'
       * @enum {string}
       */
      relationType?: "'DOCTOR'" | "'NURSE'" | "'RELATIVE'"
      /** @example null */
      user?: components['schemas']['User']
      /** @example null */
      relatedUser?: components['schemas']['User']
      /**
       * Format: date-time
       * @example 2021-03-23T16:13:08.489+01:00
       */
      createdAt?: string
      /**
       * Format: date-time
       * @example 2021-03-23T16:13:08.489+01:00
       */
      updatedAt?: string
    }
    /**
     * @description loginValidator (Validator)
     * @example {
     *       "email": "Lorem Ipsum",
     *       "password": "Lorem Ipsum"
     *     }
     */
    loginValidator: {
      /** @example Lorem Ipsum */
      email?: string
      /** @example Lorem Ipsum */
      password?: string
    }
    /**
     * @description registerValidator (Validator)
     * @example {
     *       "email": "Lorem Ipsum",
     *       "password": "Lorem Ipsum",
     *       "first_name": "Lorem Ipsum",
     *       "last_name": "Lorem Ipsum",
     *       "phone_number": "Lorem Ipsum",
     *       "address": "Lorem Ipsum",
     *       "birth_date": "Lorem Ipsum",
     *       "role": 842
     *     }
     */
    registerValidator: {
      /** @example Lorem Ipsum */
      email?: string
      /** @example Lorem Ipsum */
      password?: string
      /** @example Lorem Ipsum */
      first_name?: string
      /** @example Lorem Ipsum */
      last_name?: string
      /** @example Lorem Ipsum */
      phone_number?: string
      /** @example Lorem Ipsum */
      address?: string
      /** @example Lorem Ipsum */
      birth_date?: string
      /** @example 842 */
      role?: number
    }
    /**
     * @description getPatientsValidator (Validator)
     * @example {
     *       "id": 974
     *     }
     */
    getPatientsValidator: {
      /** @example 974 */
      id?: number
    }
    /**
     * @description getRelationsValidator (Validator)
     * @example {
     *       "id": 846
     *     }
     */
    getRelationsValidator: {
      /** @example 846 */
      id?: number
    }
    /**
     * @description linkValidator (Validator)
     * @example {
     *       "patientId": 276,
     *       "relatedUserId": 581,
     *       "relationType": 331
     *     }
     */
    linkValidator: {
      /** @example 276 */
      patientId?: number
      /** @example 581 */
      relatedUserId?: number
      /** @example 331 */
      relationType?: number
    }
    /**
     * @description unlinkValidator (Validator)
     * @example {
     *       "patientId": 576,
     *       "relatedUserId": 30,
     *       "relationType": 921
     *     }
     */
    unlinkValidator: {
      /** @example 576 */
      patientId?: number
      /** @example 30 */
      relatedUserId?: number
      /** @example 921 */
      relationType?: number
    }
    /**
     * @description deleteValidator (Validator)
     * @example {
     *       "id": 158
     *     }
     */
    deleteValidator: {
      /** @example 158 */
      id?: number
    }
    /**
     * @description listingValidator (Validator)
     * @example {
     *       "page": 177,
     *       "limit": 736,
     *       "role": 232
     *     }
     */
    listingValidator: {
      /** @example 177 */
      page?: number
      /** @example 736 */
      limit?: number
      /** @example 232 */
      role?: number
    }
    /**
     * @description showValidator (Validator)
     * @example {
     *       "id": 954
     *     }
     */
    showValidator: {
      /** @example 954 */
      id?: number
    }
    /**
     * @description updateValidator (Validator)
     * @example {
     *       "id": 264
     *     }
     */
    updateValidator: {
      /** @example 264 */
      id?: number
    }
    /**
     * @description updateValidatorBody (Validator)
     * @example {
     *       "firstName": "Lorem Ipsum",
     *       "lastName": "Lorem Ipsum",
     *       "email": "Lorem Ipsum",
     *       "phoneNumber": "Lorem Ipsum",
     *       "address": "Lorem Ipsum",
     *       "birthDate": "Lorem Ipsum",
     *       "role": 267
     *     }
     */
    updateValidatorBody: {
      /** @example Lorem Ipsum */
      firstName?: string
      /** @example Lorem Ipsum */
      lastName?: string
      /** @example Lorem Ipsum */
      email?: string
      /** @example Lorem Ipsum */
      phoneNumber?: string
      /** @example Lorem Ipsum */
      address?: string
      /** @example Lorem Ipsum */
      birthDate?: string
      /** @example 267 */
      role?: number
    }
  }
  responses: {
    /** @description Access token is missing or invalid */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content?: never
    }
    /** @description The request was accepted */
    Accepted: {
      headers: {
        [name: string]: unknown
      }
      content?: never
    }
    /** @description The resource has been created */
    Created: {
      headers: {
        [name: string]: unknown
      }
      content?: never
    }
    /** @description The resource has been created */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content?: never
    }
    /** @description The resource has been created */
    NotAcceptable: {
      headers: {
        [name: string]: unknown
      }
      content?: never
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  checkHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns **200** (OK) as **text/plain** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/plain': unknown
        }
      }
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        /** @example {
         *       "email": "Lorem Ipsum",
         *       "password": "Lorem Ipsum",
         *       "first_name": "Lorem Ipsum",
         *       "last_name": "Lorem Ipsum",
         *       "phone_number": "Lorem Ipsum",
         *       "address": "Lorem Ipsum",
         *       "birth_date": "Lorem Ipsum",
         *       "role": 842
         *     } */
        'application/json': components['schemas']['registerValidator']
      }
    }
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        /** @example {
         *       "email": "Lorem Ipsum",
         *       "password": "Lorem Ipsum"
         *     } */
        'application/json': components['schemas']['loginValidator']
      }
    }
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponseInterface']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns **401** (Unauthorized) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Returns **403** (Forbidden) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description Returns **401** (Unauthorized) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Returns **403** (Forbidden) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getPatients: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetPatientsResponseInterface']
        }
      }
      /** @description Returns **401** (Unauthorized) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Returns **403** (Forbidden) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getRelatedUsers: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetRelationsResponseInterface']
        }
      }
      /** @description Returns **401** (Unauthorized) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Returns **403** (Forbidden) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  linkPatient: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        /** @example {
         *       "patientId": 276,
         *       "relatedUserId": 581,
         *       "relationType": 331
         *     } */
        'application/json': components['schemas']['linkValidator']
      }
    }
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LinkPatientResponseInterface']
        }
      }
      /** @description Returns **401** (Unauthorized) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Returns **403** (Forbidden) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  unlinkPatient: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        /** @example {
         *       "patientId": 576,
         *       "relatedUserId": 30,
         *       "relationType": 921
         *     } */
        'application/json': components['schemas']['unlinkValidator']
      }
    }
    responses: {
      /** @description Returns **200** (OK) as **application/json** */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UnlinkPatientResponseInterface']
        }
      }
      /** @description Returns **401** (Unauthorized) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Returns **403** (Forbidden) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
