name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:frontend-latest

      - name: Copy .env.example to .env for user-service
        run: |
          cp ./backend/user-service/.env.example ./backend/user-service/.env

      - name: Build and push user-service
        uses: docker/build-push-action@v2
        with:
          context: ./backend/user-service
          file: ./backend/user-service/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:user-service-latest

      - name: Build and push alert-service
        uses: docker/build-push-action@v2
        with:
          context: ./backend/alert-service
          file: ./backend/alert-service/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:alert-service-latest

      - name: Build and push notification-service
        uses: docker/build-push-action@v2
        with:
          context: ./backend/notification-service
          file: ./backend/notification-service/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:notification-service-latest

      - name: Build and push data-service
        uses: docker/build-push-action@v2
        with:
          context: ./backend/data-service
          file: ./backend/data-service/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:data-service-latest

      - name: Build and push health-service
        uses: docker/build-push-action@v2
        with:
          context: ./backend/health-service
          file: ./backend/health-service/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:health-service-latest

      - name: Build and push smartphone
        uses: docker/build-push-action@v2
        with:
          context: ./house/smartphone
          file: ./house/smartphone/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:smartphone-latest

      - name: Build and push sensor-simulator
        uses: docker/build-push-action@v2
        with:
          context: ./house/sensor-simulator
          file: ./house/sensor-simulator/Dockerfile
          push: true
          tags: pierraad/sse-al-paddy:sensor-simulator-latest
